In [38]:
## pandas 자료구조 소개

In [39]:
import pandas as pd
import numpy as np

In [40]:
from pandas import Series, DataFrame

In [41]:
## Series
# 일련의 객체를 담을 수 있는 1차원 배열 같은 자료구조
# 어떤 NumPy 자료형이라도 담을 수 있음
# 색인 – 배열 의 연관 구조

In [5]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2=pd.Series([4,7,-5,3],index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.values

array([ 4,  7, -5,  3], dtype=int64)

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2['a']

-5

In [12]:
obj2['d']=6

In [15]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [16]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [17]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [20]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [21]:
'b' in obj2

True

In [22]:
'e' in obj2

False

In [23]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}
obj3=pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [26]:
states = ['California','Ohio','Oregon','Texas']
obj4 = pd.Series(sdata,index=states)
obj4
## NaN : Nat a Number

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [27]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [29]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [31]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [32]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [33]:
obj4.name='population'
obj4.index.name='state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [37]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [36]:
obj
obj.index = ['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [44]:
## DataFrame
# 표 같은 스프레드시트 형식의 자료구조
# R의 데이터프레임에서 유래
# 행과 열에 대한 색인을 가짐
# 색인은 같은 Series 객체를 담고 있는 파이선 사전으로 간주

In [46]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada']
        ,'year':[2000,2001,2002,2001,2002,2003],
       'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame=pd.DataFrame(data)

In [47]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [49]:
frame.head()
# 처음 5개 행 출력

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [50]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [66]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'],
                        index=['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [67]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [68]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [69]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [70]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [71]:
frame2['debt']=16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [72]:
frame2['debt']=np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [73]:
val = pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])
frame2['debt']=val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [74]:
frame2['eastern']=frame2.state=='Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [75]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
#
# DataFrame의 색인을 이용해서 얻은 열은 내부 데이터에 대한 뷰
# 이며 복사가 이루어지지 않는다. 따라서, 이렇게 얻은 Series 객체
# 대한 변경은 실제 DataFrame에 반영된다.
# 복사본이 필요할 때는 Series의 copy 메소드를 이용하라.

In [76]:
pop = {'Nevada':{2001:2.4,2002:2.9},
      'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [77]:
frame3=pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [78]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [79]:
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [80]:
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [87]:
frame3.index.name='year';frame3.columns.name='state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [88]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [89]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [92]:
obj=pd.Series(range(3),index=['a','b','c'])
index=obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [95]:
index[1:]

Index(['b', 'c'], dtype='object')

In [97]:
index[1]='d'
# Type Error
# 색인 객체는 변경 불가!

TypeError: Index does not support mutable operations

In [98]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [99]:
obj2=pd.Series([1.5,-2.5,0],index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [100]:
obj2.index is labels

True

In [101]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [102]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [103]:
'Ohio' in frame3.columns

True

In [104]:
2003 in frame3.index

False

In [106]:
dup_labels=pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [107]:
## pandas 핵심기능
# 재색인
# 하나의 행, 열 삭제하기
# 색인하기, 선택하기, 거르기
# 정수 색인
# 산술 연산과 데이터 정렬

In [108]:
# 재색인(Reindexing)

In [109]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [111]:
obj2=obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [113]:
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [115]:
obj3.reindex(range(6),method='ffill') # 누락된 값은 직전의 값으로 채움

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [119]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index=['a','c','d'],
                    columns=['Ohio','Texas','Cailfornia'])
frame

Ohio  Texas  Cailfornia
a     0      1           2
c     3      4           5
d     6      7           8

In [121]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  Cailfornia
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [122]:
states=['Texas','Utah','California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN         NaN
c      4   NaN         NaN
d      7   NaN         NaN

In [126]:
rows=['a','b','c','d']
states=['Texas','Utah','California']
frame.loc[rows, states]

Texas  Utah  California
a    1.0   NaN         NaN
b    NaN   NaN         NaN
c    4.0   NaN         NaN
d    7.0   NaN         NaN

In [129]:
# 축에서 항목 삭제하기
# drop 메서드를 사용한 삭제
# 기존 객체는 그대로 유지, 삭제된 새로운 객체를 얻음

In [130]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [131]:
new_obj=obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [132]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [133]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [134]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [135]:
obj.drop('c',inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [136]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                 index=['Ohio','Colorado','Utah','New York'],
                 columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [137]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [138]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [139]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [140]:
obj = pd.Series(np.arange(4.),index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [141]:
obj['b']

1.0

In [142]:
obj[1]

1.0

In [143]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [144]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [145]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [146]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [147]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [148]:
obj['b':'c']=5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [ ]:
# 색인하기, 선택하기, 거르기(filtering)

In [149]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio','Colorado','Utah','New York'],
                   columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [150]:
# 열 선택하기

In [151]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [152]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [153]:
# 행 선택하기

In [154]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [155]:
# 불리언 배열로 선택

In [156]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [157]:
#불리언 DataFrame으로 값 선택

In [158]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [159]:
data[data<5]=0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [162]:
# DataFrame을 라벨로 선택하기
# loc : 축 이름으로 선택, iloc : 정수 색인으로 선택

In [160]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [161]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [163]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [164]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [165]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [166]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [167]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [168]:
# 정수색인

In [173]:
ser = pd.Series(np.arange(3.))  #기본 라벨 색인 ( 라벨 0, 1, 2 )
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [171]:
ser.index

RangeIndex(start=0, stop=3, step=1)

In [172]:
ser[-1]  # 라벨 색인 2 인지 정수 색인 2인지 모호함으로 에러 발생

KeyError: -1

In [174]:
ser2=pd.Series(np.arange(3.),index=['a','b','c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [175]:
ser2.index

Index(['a', 'b', 'c'], dtype='object')

In [176]:
ser2[-1]   #라벨 색인 2 가 아니라 정수 색인 2로 명확함

2.0

In [177]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [178]:
ser[:1]

0    0.0
dtype: float64

In [179]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [180]:
ser.iloc[:1]

0    0.0
dtype: float64

In [181]:
# 산술 연산과 데이터 정렬
# 다른 색인을 가지는 객체 간의 산술 연산

In [182]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],
              index=['a','c','e','f','g'])

In [185]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [184]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [186]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [193]:
df1=pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),
                index=['Ohio','Texas','Colorado'])
df2=pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
                index=['Utah','Ohio','Texas','Oregon'])

In [194]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [195]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [196]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [198]:
df1 = pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'B':[3,4]})

In [199]:
df1

A
0  1
1  2

In [200]:
df2

B
0  3
1  4

In [201]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

In [203]:
df1=pd.DataFrame(np.arange(12.).reshape((3,4)),
                columns=list('abcd'))
df2=pd.DataFrame(np.arange(20.).reshape((4,5)),
                columns=list('abcde'))
df2.loc[1,'b']=np.nan

In [204]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [205]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [206]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [207]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [208]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [209]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [210]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [211]:
arr=np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [212]:
arr[0]

array([0., 1., 2., 3.])

In [214]:
arr-arr[0]   # 모든 행에 대해 연산 (브로드캐스팅)

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [216]:
frame=pd.DataFrame(np.arange(12.).reshape((4,3)),
                columns=list('bde'),
                  index=['Utah','Ohio','Texas','Oregon'])
series=frame.iloc[0]

In [218]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [219]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [220]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [221]:
series2 = pd.Series(range(3),index=['b','e','f'])

In [222]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [223]:
series2

b    0
e    1
f    2
dtype: int64

In [224]:
frame+series2

# 색인값을 DataFrame의 열이나 Series의 색인에서 찾을 수 없다
# 면 형식을 맞추기 위해 재색인됨

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [225]:
series3 = frame['d']

In [226]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [227]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [228]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [229]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [231]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0